### ISSUE TITLE
[PE-D][Tester D] Sample data missing

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W10-2/tp#231]
The app does not contain any sample data when first launched.
Can check whether sample data file is included.
![Screenshot 2024-04-05 155911.png](https://raw.githubusercontent.com/swtan346/ped/main/files/10bc1081-fe1c-4d77-acaf-72e189fe9b84.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: swtan346/ped#1

**Comment by jannaleong** [comment]
duplicate issue
