### ISSUE TITLE
[PE-D][Tester C] Rate Command: Rating Values

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W10-2/tp#232]
**How to reproduce:** Referring to the UG page 17, it says that rating value is from 1-5. But we can do a command `/rate ; name : Poochie ; rating : 0` to remove the rating

**Expected:** UG mentions that the user can specify rating : 0 to remove the rating for a person

**Actual:** UG only mention that rating value can be from 1 to 5 only `rating : [rating value from 1-5]`

![2-rating0.png](https://raw.githubusercontent.com/purivirakarin/ped/main/files/78e6880d-edd4-4c71-bb8d-cf5a9cd7aa7d.png)
![2-rating0AfterCommand.png](https://raw.githubusercontent.com/purivirakarin/ped/main/files/73e2b6e2-db13-45ca-95fa-159a8a93581f.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: purivirakarin/ped#2

**Comment by jannaleong** [comment]
duplicate issue
