### ISSUE TITLE
[PE-D][Tester C] Incorrect Command Example in UG: Sort

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W10-2/tp#238]
**How to reproduce:** Go the the UG Page 41 under the _Sort_ section. Execute the `/sort ; name` in the `PoochPlanner`.

**Expected:** The list of people is sorted by `name`

**Actual:** Got an incorrect command format error.

**Suggestion:** Edit `/sort ; name` into `/sort ; field : name` and change `/sort ; target-field` into `/sort ; field : target-field`

![3-sortIncorrectCommandFormat.png](https://raw.githubusercontent.com/purivirakarin/ped/main/files/67123342-0568-4d7e-8e7d-f58ccc833a15.png)

![3-sortIncorrectCommandFormat2.png](https://raw.githubusercontent.com/purivirakarin/ped/main/files/40962525-13bb-4192-86a2-163d7f13d1e9.png)

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: purivirakarin/ped#3

**Comment by jannaleong** [comment]
duplicate issue
