### ISSUE TITLE
[PE-D][Tester A] Missing space in Edit General Contact command example

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W10-2/tp#253]
Found on Page 43:

`/edit-person ; name : Poochie ; field : { address :Poochie Street 25 }`

![Screenshot 2024-04-05 at 5.10.16 PM.png](https://raw.githubusercontent.com/belligerentbeagle/ped/main/files/2e53d861-9c10-44a1-b2c7-25174b4d0798.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: belligerentbeagle/ped#5

**Comment by jannaleong** [comment]
issue with jekyll, will cut off space
