### ISSUE TITLE
[PE-D][Tester D] price does not accept cent

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W10-2/tp#263]
input: `/add-supplier ; name : PetCo ; phone : 98673098 ; address :Meow Street 24 ; email : ilovewombatstoo@gmail.com ; product: kibble ; price : $99.90/bag`

error message: `Failed to add Pooch Contact - Price should be in this format of ${amount}/{quantity}`

It is more reasonable for price to accept both dollar and cent.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: swtan346/ped#7

**Comment by jannaleong** [comment]
duplicate issue
