### ISSUE TITLE
[PE-D][Tester B] The unpin feature permits the specification of multiple names

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W10-2/tp#266]
Same as pin, when I do `/unpin ; name : Poochie ; name : Tom Tan ; name : Janna`, only the last person will be unpinned. Is it allowed to unpin multiple person at the same time, or only one at a time?

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: gosongying/ped#7

**Comment by yleeyilin** [comment]
This is an intentional enhancement to allow users to quickly rectify their command without backspacing.
