### ISSUE TITLE
[PE-D][Tester C] Command Validation: Pin command

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W10-2/tp#267]
**How to reproduce:** Execute `/pin` command twice.

**Expected:** After a person has been already pinned, and if the user pin that person again, the application should return a message that shows the person has been already pinned (instead of showing the person has been pinned sucessfully)

**Actual:** A user can pin a person multiple times

![8-dupplicatedPin.png](https://raw.githubusercontent.com/purivirakarin/ped/main/files/78a64e05-f5c7-4a9f-9031-604ea298dbe7.png)

![8-dupplicatedPin2.png](https://raw.githubusercontent.com/purivirakarin/ped/main/files/47ceddf3-9c12-4c67-bbb9-3ad575c10526.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: purivirakarin/ped#8

**Comment by yleeyilin** [comment]
This is a feature flaw and cannot be fixed in v1.4.
