### ISSUE TITLE
[PE-D][Tester C] Deadline Data Validation from JSON file

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W10-2/tp#269]
**How to reproduce:** Edit the value of deadline in JSON file and run the application again.

**Expected:** Application should report that the data of that deadline field is invalid, then it could show deadline as empty or just remove it.

**Actual:** Currently, the application show the invalid deadline without warning anything.

![10-InvalidDeadlineValueJSON.png](https://raw.githubusercontent.com/purivirakarin/ped/main/files/7542bd91-3c8b-4931-8136-62027e1e5a53.png)

![10-InvalidDeadlineValueJSON2.png](https://raw.githubusercontent.com/purivirakarin/ped/main/files/4a438646-8028-4510-9b62-d32f8606fcc8.png)

![10-InvalidDeadlineValueJSON3.png](https://raw.githubusercontent.com/purivirakarin/ped/main/files/9b52afe7-6c23-441a-b06a-1f0bbeb3ee57.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: purivirakarin/ped#10

**Comment by jamessinmaojun** [comment]
Not feature flaw, fix in UG
