### ISSUE TITLE
[PE-D][Tester D] Duplicate phone number allowed

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W10-2/tp#271]
I does not make sense for multiple person to have the same phone number, every person should have a unique phone number. Can do checking when adding or editing person.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: swtan346/ped#9

**Comment by jannaleong** [comment]
1 company can offer multiple services.

For eg, companies can redirect customers when they call the same line based on the nature of their queries.
