### ISSUE TITLE
[PE-D][Tester A] Price should allow cents

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W10-2/tp#278]
Sometimes products can cost less than a dollar, and may not always be an integer amount. 

Currently, price does not allow the value to include cents.

![Screenshot 2024-04-05 at 9.27.55 PM.png](https://raw.githubusercontent.com/belligerentbeagle/ped/main/files/1e63ba7f-da6d-406b-ad42-8a2568be58c7.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: belligerentbeagle/ped#10

**Comment by jannaleong** [comment]
feature flaw - should allow for more units in pricing (Not allowed to fix in v1.4)
