### ISSUE TITLE
[PE-D][Tester D] Inappropriate digit range for phone number

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W10-2/tp#287]
Only emergency numbers are 3 digits, and they will not be phone number for person, staff, supplier or maintainer. So, it will be better for the minimum digit count to be set to a more realistic range, e.g. Singapore phone number have 8 digits.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: swtan346/ped#17

**Comment by jannaleong** [comment]
We want to cater to all users and allow for flexibility in the phone numbers. As stated by the tester, 3 digit numbers are allowed and could fall under maintainers(emergency vets). 

Furthermore, different countries have different lengths of phone numbers. We would like to cater to international users.

Thus we do not believe this is a feature flaw.
