### ISSUE TITLE
Help Command Bugs

### ISSUE THREAD

**Issue by chiageng** [AY2324S2-CS2103T-W10-2/tp#66]
Change format of help to /help

/help ; command : [command] doesnt show any distinct difference with /help

Is it a better idea to display format command and command example directly as success message? You can directly achieve this by calling CONSTANT HELP from each Command class.

Should we add /list-commands to help users? Should be easy to achieve this by listing all type of commands

Standardise maintainer (i.e. shouldn't use maintainance in code)

**Comment by jannaleong** [comment]
i do not think we need a /list-commands because the users can refer to our user guide:)

I would correct maintainance to maintainer.

i will change the help commnad to be more user friendly. i believe this is why u see the same window.
