### ISSUE TITLE
Fix Note Feature bugs

### ISSUE THREAD

**Issue by chiageng** [AY2324S2-CS2103T-W10-2/tp#96]
1. List Card for every Person will show a blank row when no note exist

2. Note command does not display error messages

Command to replicate : 
```
/note
/note ;
/note ; name : John Doe other
```
Current behaviour : Show an exception on IDE, but doesnt display any error messages
Expected behaviour : Display accurate error messages such as "Wrong command format"

3. Missing field in note command
Command to replicate : 
```
/note ; name : John Doe other ; 
```
Current behaviour : Display a messy error messages
Expected behaviour : Display a neat and accurate error messages such as "Wrong command format"

4. Note command doesnt work on other Person type. Handle this in v1.3 iteration.

**Comment by jannaleong** [comment]
Additionally bugs to fix:

1) abstract out notecommand execute function more as code is lengthy.
2) change curr to model for clarity in jsonadapterperson.java
3) test execution failures
